### ISSUE TITLE
Logging in from settings fails

### ISSUE THREAD

**Issue by MrCustomizer** [MrCustomizer/palaver#39]
MTRNord reports this error:
```
java.lang.IllegalStateException: You have to be successfully logged in before using this class!
	at de.localtoast.palaver.sys.PalaverHttpClient.<init>(PalaverHttpClient.kt:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at tornadofx.FXKt.find(FX.kt:408)
	at de.localtoast.palaver.sys.SyncController$$special$$inlined$inject$1.getValue(Component.kt:952)
	at de.localtoast.palaver.sys.SyncController$$special$$inlined$inject$1.getValue(Component.kt:156)
	at de.localtoast.palaver.sys.SyncController.getClient(SyncController.kt)
	at de.localtoast.palaver.sys.SyncController.sync(SyncController.kt:60)
	at de.localtoast.palaver.sys.SyncController.sync$default(SyncController.kt:56)
	at de.localtoast.palaver.sys.SyncController.startSyncing(SyncController.kt:37)
	at de.localtoast.palaver.gui.MainWindow$initConnection$1.invoke(MainWindow.kt:77)
	at de.localtoast.palaver.gui.MainWindow$initConnection$1.invoke(MainWindow.kt:42)
	at tornadofx.FXTask.call(Async.kt:416)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by MrCustomizer** [comment]
It has potentially something to do with the way the Matrix ID is built on logging with the data from the settings file. It's probably best to just save the ID instead of the username.
Also: Check `ConnectionInitializer::initializeFromSettings`: It's possible that this method gracefully finishes, even if something during the login process has horribly gone wrong.
