### ISSUE TITLE
Problems while dragging avatars in backlog view

### ISSUE THREAD

**Issue by MrCustomizer** [MrCustomizer/palaver#47]
In Linux, an exception is thrown:
```
java.lang.IllegalArgumentException: Invalid URL: unknown protocol: data
	at javafx.scene.image.Image.validateUrl(Image.java:1121)
	at javafx.scene.image.Image.<init>(Image.java:620)
	at com.sun.javafx.tk.quantum.QuantumClipboard.readImage(QuantumClipboard.java:400)
	at com.sun.javafx.tk.quantum.QuantumClipboard.getContent(QuantumClipboard.java:291)
	at javafx.scene.input.Clipboard.getContentImpl(Clipboard.java:261)
	at javafx.scene.input.Dragboard.getContentImpl(Dragboard.java:62)
	at javafx.scene.input.Clipboard.getContent(Clipboard.java:254)
	at javafx.scene.web.WebView.lambda$registerEventHandlers$35(WebView.java:1194)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$DnDGesture.handleExitEnter(Scene.java:3210)
	at javafx.scene.Scene$DnDGesture.processTargetEnterOver(Scene.java:3098)
	at javafx.scene.Scene$DnDGesture.access$6100(Scene.java:2909)
	at javafx.scene.Scene$DropTargetListener.dragEnter(Scene.java:2813)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragEnter$306(GlassSceneDnDEventHandler.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragEnter(GlassSceneDnDEventHandler.java:65)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragEnter$360(GlassViewEventHandler.java:706)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragEnter(GlassViewEventHandler.java:705)
	at com.sun.glass.ui.View.handleDragEnter(View.java:688)
	at com.sun.glass.ui.View.notifyDragEnter(View.java:1020)
	at com.sun.glass.ui.gtk.GtkDnDClipboard.pushToSystemImpl(Native Method)
	at com.sun.glass.ui.gtk.GtkDnDClipboard.pushToSystem(GtkDnDClipboard.java:39)
	at com.sun.glass.ui.SystemClipboard.flush(SystemClipboard.java:51)
	at com.sun.glass.ui.ClipboardAssistance.flush(ClipboardAssistance.java:59)
	at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:274)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1231)
	at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:2953)
	at javafx.scene.Scene$DnDGesture.process(Scene.java:3022)
	at javafx.scene.Scene$DnDGesture.access$8200(Scene.java:2909)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3773)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.MalformedURLException: unknown protocol: data
	at java.net.URL.<init>(URL.java:600)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at javafx.scene.image.Image.validateUrl(Image.java:1115)
	... 56 more

```
In Windows, the avatar image gets stuck on the screen and stays on this exact position, even if the window is moved to another location.

**Comment by MrCustomizer** [comment]
This is probably the same problem: https://stackoverflow.com/questions/45398912/unknown-protocol-data-when-using-data-uris-in-img-tags-displayed-by-javafx-we

**Comment by MrCustomizer** [comment]
https://bugs.openjdk.java.net/browse/JDK-8160597

**Comment by MrCustomizer** [comment]
https://stackoverflow.com/questions/22984430/javafx2-webview-and-in-memory-images
